import type { KnowledgeCategory } from "@/lib/design/knowledge-engine/types";
import type { VisionCardAnalysis, WBProductCard } from "./types";

const CATEGORY_VISION_PROFILES: Record<
  KnowledgeCategory,
  Omit<VisionCardAnalysis, "designDNA" | "estimatedCTR">
> = {
  tools: {
    productScale: 56,
    negativeSpace: 18,
    textDensity: 0.38,
    headlinePosition: "top-left",
    badgeCount: 2,
    backgroundType: "white_studio",
    lighting: "flat_studio",
    composition: "product_left",
    cameraAngle: "three-quarter",
    primaryColor: "#ffffff",
    fontStyle: "bold_sans",
    visualHierarchy: "text_first",
    depth: "flat",
    storytelling: "specs_list",
  },
  electronics: {
    productScale: 58,
    negativeSpace: 22,
    textDensity: 0.35,
    headlinePosition: "top",
    badgeCount: 2,
    backgroundType: "gradient_tech",
    lighting: "cool_studio",
    composition: "hero_center",
    cameraAngle: "low_hero",
    primaryColor: "#0f172a",
    fontStyle: "geometric_sans",
    visualHierarchy: "product_first",
    depth: "subtle_shadow",
    storytelling: "feature_highlight",
  },
  cosmetics: {
    productScale: 52,
    negativeSpace: 28,
    textDensity: 0.32,
    headlinePosition: "top-right",
    badgeCount: 1,
    backgroundType: "soft_gradient",
    lighting: "beauty_soft",
    composition: "minimal_center",
    cameraAngle: "frontal",
    primaryColor: "#fce7f3",
    fontStyle: "elegant_serif",
    visualHierarchy: "product_first",
    depth: "soft_bokeh",
    storytelling: "luxury_mood",
  },
  furniture: {
    productScale: 60,
    negativeSpace: 20,
    textDensity: 0.3,
    headlinePosition: "bottom-left",
    badgeCount: 1,
    backgroundType: "interior_scene",
    lighting: "warm_ambient",
    composition: "lifestyle",
    cameraAngle: "eye_level",
    primaryColor: "#d6d3d1",
    fontStyle: "modern_sans",
    visualHierarchy: "balanced",
    depth: "room_depth",
    storytelling: "home_context",
  },
  kids: {
    productScale: 62,
    negativeSpace: 16,
    textDensity: 0.42,
    headlinePosition: "top",
    badgeCount: 3,
    backgroundType: "colorful_flat",
    lighting: "bright_even",
    composition: "playful_diagonal",
    cameraAngle: "slight_high",
    primaryColor: "#fef08a",
    fontStyle: "rounded_display",
    visualHierarchy: "badge_heavy",
    depth: "flat",
    storytelling: "fun_emotion",
  },
  clothes: {
    productScale: 64,
    negativeSpace: 24,
    textDensity: 0.28,
    headlinePosition: "top-left",
    badgeCount: 1,
    backgroundType: "neutral_studio",
    lighting: "fashion_soft",
    composition: "editorial",
    cameraAngle: "three-quarter",
    primaryColor: "#f5f5f4",
    fontStyle: "editorial_sans",
    visualHierarchy: "product_first",
    depth: "subtle",
    storytelling: "style_mood",
  },
  auto: {
    productScale: 55,
    negativeSpace: 18,
    textDensity: 0.36,
    headlinePosition: "top-left",
    badgeCount: 2,
    backgroundType: "dark_garage",
    lighting: "dramatic",
    composition: "product_right",
    cameraAngle: "low_angle",
    primaryColor: "#1c1917",
    fontStyle: "industrial_sans",
    visualHierarchy: "specs_first",
    depth: "contrast",
    storytelling: "power_specs",
  },
  pets: {
    productScale: 58,
    negativeSpace: 20,
    textDensity: 0.34,
    headlinePosition: "top",
    badgeCount: 2,
    backgroundType: "warm_home",
    lighting: "natural_warm",
    composition: "friendly_center",
    cameraAngle: "eye_level",
    primaryColor: "#fef3c7",
    fontStyle: "friendly_sans",
    visualHierarchy: "emotion_first",
    depth: "cozy",
    storytelling: "care_benefit",
  },
  kitchen: {
    productScale: 57,
    negativeSpace: 19,
    textDensity: 0.37,
    headlinePosition: "top-left",
    badgeCount: 2,
    backgroundType: "white_kitchen",
    lighting: "bright_clean",
    composition: "counter_scene",
    cameraAngle: "three-quarter",
    primaryColor: "#ffffff",
    fontStyle: "clean_sans",
    visualHierarchy: "feature_list",
    depth: "kitchen_context",
    storytelling: "utility_specs",
  },
  sports: {
    productScale: 61,
    negativeSpace: 21,
    textDensity: 0.33,
    headlinePosition: "top-right",
    badgeCount: 2,
    backgroundType: "dynamic_gradient",
    lighting: "energetic",
    composition: "diagonal_action",
    cameraAngle: "dynamic_low",
    primaryColor: "#0ea5e9",
    fontStyle: "bold_condensed",
    visualHierarchy: "energy_first",
    depth: "motion_blur_hint",
    storytelling: "performance",
  },
  home: {
    productScale: 56,
    negativeSpace: 20,
    textDensity: 0.35,
    headlinePosition: "top-left",
    badgeCount: 2,
    backgroundType: "white_studio",
    lighting: "flat_studio",
    composition: "product_center",
    cameraAngle: "three-quarter",
    primaryColor: "#ffffff",
    fontStyle: "neutral_sans",
    visualHierarchy: "balanced",
    depth: "minimal",
    storytelling: "household_benefit",
  },
  generator: {
    productScale: 54,
    negativeSpace: 16,
    textDensity: 0.4,
    headlinePosition: "top-left",
    badgeCount: 3,
    backgroundType: "white_studio",
    lighting: "flat_studio",
    composition: "specs_heavy",
    cameraAngle: "three-quarter",
    primaryColor: "#ffffff",
    fontStyle: "bold_sans",
    visualHierarchy: "text_first",
    depth: "flat",
    storytelling: "power_numbers",
  },
  generic: {
    productScale: 55,
    negativeSpace: 20,
    textDensity: 0.35,
    headlinePosition: "top-left",
    badgeCount: 2,
    backgroundType: "white_studio",
    lighting: "flat_studio",
    composition: "standard",
    cameraAngle: "three-quarter",
    primaryColor: "#ffffff",
    fontStyle: "sans",
    visualHierarchy: "balanced",
    depth: "flat",
    storytelling: "generic_offer",
  },
};

function jitter(value: number, spread: number, seed: number): number {
  const delta = ((seed % 100) / 100 - 0.5) * spread;
  return Number((value + delta).toFixed(1));
}

export function analyzeCardVision(
  card: WBProductCard,
  category: KnowledgeCategory,
  index: number,
): VisionCardAnalysis {
  const base = CATEGORY_VISION_PROFILES[category] ?? CATEGORY_VISION_PROFILES.generic;
  const popularityBoost = Math.min(8, Math.log10(Math.max(10, card.feedbacks)) * 2);
  const ratingBoost = (card.rating - 4) * 5;

  return {
    productScale: jitter(base.productScale, 6, card.id + index),
    negativeSpace: jitter(base.negativeSpace, 8, card.id),
    textDensity: jitter(base.textDensity * 100, 10, index) / 100,
    headlinePosition: base.headlinePosition,
    badgeCount: Math.max(0, Math.round(base.badgeCount + (index % 2))),
    backgroundType: base.backgroundType,
    lighting: base.lighting,
    composition: base.composition,
    cameraAngle: base.cameraAngle,
    primaryColor: base.primaryColor,
    fontStyle: base.fontStyle,
    visualHierarchy: base.visualHierarchy,
    depth: base.depth,
    storytelling: base.storytelling,
    estimatedCTR: Number(
      Math.min(12, 4.5 + popularityBoost * 0.3 + ratingBoost * 0.2).toFixed(1),
    ),
    designDNA: `${base.composition}_${base.backgroundType}_${base.fontStyle}`,
  };
}

export function analyzeCardsBatch(
  cards: WBProductCard[],
  category: KnowledgeCategory,
): VisionCardAnalysis[] {
  return cards.map((card, index) => analyzeCardVision(card, category, index));
}
