import type { CompositionConstraints, CompositionTemplateId } from "./types";

export const COMPOSITION_TEMPLATES: Record<CompositionTemplateId, CompositionConstraints> = {
  hero_left: {
    id: "hero_left",
    label: "Hero Left",
    heroSide: "left",
    heroWidth: [0.4, 0.48],
    heroHeight: [0.42, 0.52],
    headlineWidth: [0.32, 0.38],
    headlineHeight: [0.14, 0.2],
    whitespaceTarget: [0.22, 0.32],
    maxSecondaryObjects: 2,
    maxDecorativeObjects: 1,
    allowSymmetry: false,
    layoutEngineTemplate: "hero_left",
  },
  hero_right: {
    id: "hero_right",
    label: "Hero Right",
    heroSide: "right",
    heroWidth: [0.4, 0.48],
    heroHeight: [0.42, 0.52],
    headlineWidth: [0.3, 0.36],
    headlineHeight: [0.14, 0.2],
    whitespaceTarget: [0.22, 0.32],
    maxSecondaryObjects: 2,
    maxDecorativeObjects: 1,
    allowSymmetry: false,
    layoutEngineTemplate: "hero_right",
  },
  hero_bottom: {
    id: "hero_bottom",
    label: "Hero Bottom",
    heroSide: "bottom",
    heroWidth: [0.5, 0.62],
    heroHeight: [0.38, 0.48],
    headlineWidth: [0.34, 0.42],
    headlineHeight: [0.12, 0.18],
    whitespaceTarget: [0.2, 0.3],
    maxSecondaryObjects: 2,
    maxDecorativeObjects: 1,
    allowSymmetry: false,
    layoutEngineTemplate: "commercial",
  },
  hero_center: {
    id: "hero_center",
    label: "Hero Center",
    heroSide: "center-offset",
    heroWidth: [0.38, 0.46],
    heroHeight: [0.4, 0.5],
    headlineWidth: [0.3, 0.36],
    headlineHeight: [0.12, 0.18],
    whitespaceTarget: [0.25, 0.35],
    maxSecondaryObjects: 1,
    maxDecorativeObjects: 0,
    allowSymmetry: false,
    layoutEngineTemplate: "minimal",
  },
  diagonal: {
    id: "diagonal",
    label: "Diagonal",
    heroSide: "right",
    heroWidth: [0.42, 0.5],
    heroHeight: [0.44, 0.54],
    headlineWidth: [0.28, 0.34],
    headlineHeight: [0.14, 0.2],
    whitespaceTarget: [0.2, 0.28],
    maxSecondaryObjects: 2,
    maxDecorativeObjects: 1,
    allowSymmetry: false,
    layoutEngineTemplate: "diagonal",
  },
  premium_minimal: {
    id: "premium_minimal",
    label: "Premium Minimal",
    heroSide: "right",
    heroWidth: [0.36, 0.44],
    heroHeight: [0.4, 0.48],
    headlineWidth: [0.28, 0.34],
    headlineHeight: [0.12, 0.16],
    whitespaceTarget: [0.28, 0.35],
    maxSecondaryObjects: 1,
    maxDecorativeObjects: 0,
    allowSymmetry: false,
    layoutEngineTemplate: "premium",
  },
  luxury_split: {
    id: "luxury_split",
    label: "Luxury Split",
    heroSide: "right",
    heroWidth: [0.44, 0.5],
    heroHeight: [0.46, 0.54],
    headlineWidth: [0.3, 0.36],
    headlineHeight: [0.14, 0.18],
    whitespaceTarget: [0.24, 0.32],
    maxSecondaryObjects: 2,
    maxDecorativeObjects: 1,
    allowSymmetry: false,
    layoutEngineTemplate: "split",
  },
  technical: {
    id: "technical",
    label: "Technical",
    heroSide: "right",
    heroWidth: [0.4, 0.48],
    heroHeight: [0.4, 0.5],
    headlineWidth: [0.32, 0.38],
    headlineHeight: [0.14, 0.2],
    whitespaceTarget: [0.2, 0.28],
    maxSecondaryObjects: 3,
    maxDecorativeObjects: 1,
    allowSymmetry: false,
    layoutEngineTemplate: "technical",
  },
  comparison: {
    id: "comparison",
    label: "Comparison",
    heroSide: "center-offset",
    heroWidth: [0.38, 0.44],
    heroHeight: [0.38, 0.46],
    headlineWidth: [0.34, 0.4],
    headlineHeight: [0.12, 0.16],
    whitespaceTarget: [0.22, 0.3],
    maxSecondaryObjects: 3,
    maxDecorativeObjects: 1,
    allowSymmetry: true,
    layoutEngineTemplate: "grid",
  },
  feature_focus: {
    id: "feature_focus",
    label: "Feature Focus",
    heroSide: "right",
    heroWidth: [0.42, 0.5],
    heroHeight: [0.44, 0.52],
    headlineWidth: [0.3, 0.36],
    headlineHeight: [0.12, 0.18],
    whitespaceTarget: [0.2, 0.28],
    maxSecondaryObjects: 2,
    maxDecorativeObjects: 1,
    allowSymmetry: false,
    layoutEngineTemplate: "focus",
  },
  lifestyle: {
    id: "lifestyle",
    label: "Lifestyle",
    heroSide: "right",
    heroWidth: [0.4, 0.48],
    heroHeight: [0.42, 0.5],
    headlineWidth: [0.32, 0.38],
    headlineHeight: [0.14, 0.2],
    whitespaceTarget: [0.22, 0.3],
    maxSecondaryObjects: 2,
    maxDecorativeObjects: 1,
    allowSymmetry: false,
    layoutEngineTemplate: "lifestyle",
  },
  gallery: {
    id: "gallery",
    label: "Gallery",
    heroSide: "center-offset",
    heroWidth: [0.44, 0.52],
    heroHeight: [0.44, 0.52],
    headlineWidth: [0.28, 0.34],
    headlineHeight: [0.1, 0.14],
    whitespaceTarget: [0.26, 0.34],
    maxSecondaryObjects: 1,
    maxDecorativeObjects: 0,
    allowSymmetry: false,
    layoutEngineTemplate: "magazine",
  },
};

export function resolveCompositionTemplate(input: {
  category: import("@/lib/product-analysis").ProductCategory;
  priceSegment: string;
  sceneType?: string;
  genomeTemplateId?: string;
}): CompositionTemplateId {
  const genomeMap: Partial<Record<string, CompositionTemplateId>> = {
    hero_left: "hero_left",
    hero_right: "hero_right",
    minimal: "premium_minimal",
    premium: "premium_minimal",
    luxury: "luxury_split",
    diagonal: "diagonal",
    technical: "technical",
    lifestyle: "lifestyle",
    split: "luxury_split",
    focus: "feature_focus",
    grid: "comparison",
    magazine: "gallery",
  };
  if (input.genomeTemplateId && genomeMap[input.genomeTemplateId]) {
    return genomeMap[input.genomeTemplateId]!;
  }
  if (input.sceneType === "lifestyle") return "lifestyle";
  if (input.sceneType === "technology") return "technical";
  if (input.priceSegment === "premium") return "premium_minimal";
  if (input.category === "electronics") return "technical";
  if (input.category === "fashion") return "gallery";
  return "hero_right";
}
