import type { CommercialRuleBeta } from "./types";

const EKB = "experimental_knowledge_base_v1" as const;

function rule(
  partial: Omit<CommercialRuleBeta, "source" | "confidence" | "priority"> & {
    priority?: number;
    confidence?: number;
    source?: CommercialRuleBeta["source"];
  },
): CommercialRuleBeta {
  return {
    priority: 90,
    confidence: 0.92,
    source: EKB,
    ...partial,
  };
}

/** Experimental Knowledge Base v1.0 — 50 Wildberries Hero rules (runtime SSOT). */
export const WILDBERRIES_HERO_RULES: CommercialRuleBeta[] = [
  // ── Hero Design ──────────────────────────────────────────────────────
  rule({
    id: "WB-HERO-001",
    title: "Hero sells interest",
    category: "hero",
    priority: 100,
    appliesTo: ["wildberries", "hero"],
    rule: "Hero продаёт интерес, а не объясняет товар.",
    decisionImpact: "mainMessage result-oriented; avoid spec dump",
  }),
  rule({
    id: "WB-HERO-002",
    title: "One main idea",
    category: "hero",
    priority: 98,
    appliesTo: ["wildberries", "hero"],
    rule: "Hero содержит одну главную идею.",
    decisionImpact: "maxCharacteristics capped; single headline focus",
  }),
  rule({
    id: "WB-HERO-003",
    title: "Max 3-4 characteristics",
    category: "hero",
    priority: 97,
    appliesTo: ["wildberries", "hero"],
    rule: "Hero содержит максимум 3–4 характеристики.",
    decisionImpact: "maxCharacteristics=4",
  }),
  rule({
    id: "WB-HERO-004",
    title: "Minimal graphic elements",
    category: "hero",
    priority: 95,
    appliesTo: ["wildberries", "hero"],
    rule: "Hero содержит минимум графических элементов.",
    decisionImpact: "badgeLimit=2; reduce decorative clutter",
  }),
  rule({
    id: "WB-HERO-005",
    title: "Product is visual hero",
    category: "hero",
    priority: 100,
    appliesTo: ["wildberries", "hero"],
    rule: "Товар является главным визуальным объектом.",
    decisionImpact: "heroDominance=product_first",
  }),
  rule({
    id: "WB-HERO-006",
    title: "Product area 50-60%",
    category: "hero",
    priority: 96,
    appliesTo: ["wildberries", "hero"],
    rule: "Товар должен занимать примерно 50–60% площади Hero.",
    decisionImpact: "productAreaTarget=0.55",
  }),
  rule({
    id: "WB-HERO-007",
    title: "Thumbnail readability",
    category: "hero",
    priority: 94,
    appliesTo: ["wildberries", "hero"],
    rule: "Hero должен работать в миниатюре WB.",
    decisionImpact: "high contrast; large product; minimal fine text",
  }),

  // ── Visual Hierarchy ─────────────────────────────────────────────────
  rule({
    id: "WB-HIER-001",
    title: "Attention order",
    category: "hierarchy",
    priority: 95,
    appliesTo: ["wildberries", "hierarchy"],
    rule: "Порядок внимания: товар → заголовок → характеристики → логотип.",
    decisionImpact: "visualHierarchy product,headline,characteristics,logo",
  }),
  rule({
    id: "WB-HIER-002",
    title: "Logo does not compete",
    category: "hierarchy",
    priority: 88,
    appliesTo: ["wildberries", "hierarchy"],
    rule: "Логотип не конкурирует с товаром.",
    decisionImpact: "logo minimal weight; corner placement",
  }),
  rule({
    id: "WB-HIER-003",
    title: "Badge minimal weight",
    category: "hierarchy",
    priority: 87,
    appliesTo: ["wildberries", "hierarchy"],
    rule: "Бейджи имеют минимальный визуальный вес.",
    decisionImpact: "badgeLimit=2",
  }),
  rule({
    id: "WB-HIER-004",
    title: "Justify every element",
    category: "hierarchy",
    priority: 90,
    appliesTo: ["wildberries", "hierarchy"],
    rule: "Каждый элемент должен оправдывать присутствие.",
    decisionImpact: "remove non-selling elements",
  }),
  rule({
    id: "WB-HIER-005",
    title: "Remove non-sellers",
    category: "hierarchy",
    priority: 91,
    appliesTo: ["wildberries", "hierarchy"],
    rule: "Если элемент ничего не продаёт — удалить.",
    decisionImpact: "strict element budget",
  }),

  // ── Typography ───────────────────────────────────────────────────────
  rule({
    id: "WB-TYPE-001",
    title: "One main message",
    category: "typography",
    priority: 94,
    appliesTo: ["wildberries", "typography"],
    rule: "Одно главное сообщение.",
    decisionImpact: "typographyDirection single headline",
  }),
  rule({
    id: "WB-TYPE-002",
    title: "Text sells result",
    category: "typography",
    priority: 96,
    appliesTo: ["wildberries", "typography"],
    rule: "Текст продаёт результат, а не категорию.",
    decisionImpact: "mainMessage result-oriented",
  }),
  rule({
    id: "WB-TYPE-003",
    title: "Result over specs",
    category: "typography",
    priority: 93,
    appliesTo: ["wildberries", "typography"],
    rule: "Результат сильнее характеристик.",
    decisionImpact: "headline = benefit; bullets = proof",
  }),
  rule({
    id: "WB-TYPE-004",
    title: "Specs confirm promise",
    category: "typography",
    priority: 90,
    appliesTo: ["wildberries", "typography"],
    rule: "Характеристики подтверждают обещание.",
    decisionImpact: "characteristics support headline only",
  }),
  rule({
    id: "WB-TYPE-005",
    title: "Grammar required",
    category: "typography",
    priority: 85,
    appliesTo: ["wildberries", "typography"],
    rule: "Грамматика обязательна.",
    decisionImpact: "quality gate on copy",
  }),
  rule({
    id: "WB-TYPE-006",
    title: "Declension and line breaks",
    category: "typography",
    priority: 84,
    appliesTo: ["wildberries", "typography"],
    rule: "Склонения и переносы обязательны к проверке.",
    decisionImpact: "typography QA before render",
  }),

  // ── Commercial Psychology ────────────────────────────────────────────
  rule({
    id: "WB-PSY-001",
    title: "Buy outcome not specs",
    category: "psychology",
    priority: 97,
    appliesTo: ["wildberries", "psychology"],
    rule: "Люди покупают результат, а не характеристики.",
    decisionImpact: "mainMessage outcome framing",
  }),
  rule({
    id: "WB-PSY-002",
    title: "Hero sells promise",
    category: "psychology",
    priority: 96,
    appliesTo: ["wildberries", "psychology"],
    rule: "Hero продаёт обещание.",
    decisionImpact: "emotional promise in headline",
  }),
  rule({
    id: "WB-PSY-003",
    title: "Hero evokes emotion",
    category: "psychology",
    priority: 92,
    appliesTo: ["wildberries", "psychology"],
    rule: "Hero вызывает эмоцию.",
    decisionImpact: "environment supports emotion",
  }),
  rule({
    id: "WB-PSY-004",
    title: "First photo opens card",
    category: "psychology",
    priority: 98,
    appliesTo: ["wildberries", "psychology"],
    rule: "Первое фото должно мотивировать открыть карточку.",
    decisionImpact: "CTR-first composition",
  }),
  rule({
    id: "WB-PSY-005",
    title: "Other photos prove promise",
    category: "psychology",
    priority: 88,
    appliesTo: ["wildberries", "psychology"],
    rule: "Остальные фото доказывают обещание Hero.",
    decisionImpact: "slide 2+ = proof not new promise",
  }),

  // ── Environment ──────────────────────────────────────────────────────
  rule({
    id: "WB-ENV-001",
    title: "Background is commercial tool",
    category: "environment",
    priority: 90,
    appliesTo: ["wildberries", "environment"],
    rule: "Фон является коммерческим инструментом.",
    decisionImpact: "environmentDirection explicit",
  }),
  rule({
    id: "WB-ENV-002",
    title: "Background supports psychology",
    category: "environment",
    priority: 89,
    appliesTo: ["wildberries", "environment"],
    rule: "Фон усиливает психологию покупки.",
    decisionImpact: "match environment to audience intent",
  }),
  rule({
    id: "WB-ENV-003",
    title: "No universal background",
    category: "environment",
    priority: 87,
    appliesTo: ["wildberries", "environment"],
    rule: "Фон не должен повторяться для всех категорий.",
    decisionImpact: "category-specific environment",
  }),
  rule({
    id: "WB-ENV-004",
    title: "Usage scenario environment",
    category: "environment",
    priority: 91,
    appliesTo: ["wildberries", "environment"],
    rule: "Environment выбирается по сценарию использования.",
    decisionImpact: "productType drives environment",
  }),
  rule({
    id: "WB-ENV-005",
    title: "Lifestyle light modern",
    category: "environment",
    priority: 86,
    appliesTo: ["wildberries", "environment", "lifestyle", "home"],
    rule: "Для lifestyle категорий светлый современный фон.",
    decisionImpact: "environmentDirection=light_modern_clean",
  }),
  rule({
    id: "WB-ENV-006",
    title: "Professional industrial scene",
    category: "environment",
    priority: 86,
    appliesTo: ["wildberries", "environment", "professional", "tool"],
    rule: "Для профессионального инструмента допустима индустриальная сцена.",
    decisionImpact: "environmentDirection=clean_industrial_technical",
  }),
  rule({
    id: "WB-ENV-007",
    title: "Audience-matched environment",
    category: "environment",
    priority: 85,
    appliesTo: ["wildberries", "environment"],
    rule: "Environment должен соответствовать целевой аудитории.",
    decisionImpact: "audience influences scene",
  }),

  // ── Differentiation ──────────────────────────────────────────────────
  rule({
    id: "WB-DIFF-001",
    title: "Seek competitor difference",
    category: "differentiation",
    priority: 88,
    appliesTo: ["wildberries", "differentiation"],
    rule: "DAOS должен искать отличие от конкурентов.",
    decisionImpact: "contrast direction vs category norm",
  }),
  rule({
    id: "WB-DIFF-002",
    title: "Analyze neighbor cards",
    category: "differentiation",
    priority: 87,
    appliesTo: ["wildberries", "differentiation"],
    rule: "Анализировать соседние карточки категории.",
    decisionImpact: "market intelligence input",
  }),
  rule({
    id: "WB-DIFF-003",
    title: "Light wins in dark category",
    category: "differentiation",
    priority: 86,
    appliesTo: ["wildberries", "differentiation"],
    rule: "Иногда светлая карточка выигрывает, если остальные тёмные.",
    decisionImpact: "backgroundContrastDirection adaptive",
  }),
  rule({
    id: "WB-DIFF-004",
    title: "Controlled distinction",
    category: "differentiation",
    priority: 85,
    appliesTo: ["wildberries", "differentiation"],
    rule: "Отличие должно быть контролируемым.",
    decisionImpact: "no random novelty; rule-bound contrast",
  }),

  // ── Brand DNA ────────────────────────────────────────────────────────
  rule({
    id: "WB-BRAND-001",
    title: "Brand DNA does not replace DAOS",
    category: "brand",
    priority: 80,
    appliesTo: ["wildberries", "brand"],
    rule: "Brand DNA не заменяет DAOS.",
    decisionImpact: "commercial rules override brand defaults",
  }),
  rule({
    id: "WB-BRAND-002",
    title: "Brand DNA design params only",
    category: "brand",
    priority: 81,
    appliesTo: ["wildberries", "brand"],
    rule: "Brand DNA влияет только на параметры дизайна.",
    decisionImpact: "palette/font only; not commercial strategy",
  }),
  rule({
    id: "WB-BRAND-003",
    title: "Do not copy brands",
    category: "brand",
    priority: 82,
    appliesTo: ["wildberries", "brand"],
    rule: "Не копировать бренды.",
    decisionImpact: "principles not trademarks",
  }),
  rule({
    id: "WB-BRAND-004",
    title: "Design principles only",
    category: "brand",
    priority: 81,
    appliesTo: ["wildberries", "brand"],
    rule: "Использовать только дизайн-принципы.",
    decisionImpact: "abstract brand traits only",
  }),

  // ── Research ─────────────────────────────────────────────────────────
  rule({
    id: "WB-RES-001",
    title: "Research before design",
    category: "research",
    priority: 83,
    appliesTo: ["wildberries", "research"],
    rule: "Перед дизайном проводится исследование.",
    decisionImpact: "research rules inform copy and USP",
  }),
  rule({
    id: "WB-RES-002",
    title: "Verify characteristics by SKU",
    category: "research",
    priority: 84,
    appliesTo: ["wildberries", "research"],
    rule: "Характеристики проверяются по артикулу и официальному сайту.",
    decisionImpact: "facts from official sources",
  }),
  rule({
    id: "WB-RES-003",
    title: "USP from official sources",
    category: "research",
    priority: 85,
    appliesTo: ["wildberries", "research"],
    rule: "УТП собираются из официальных источников и отзывов.",
    decisionImpact: "mainMessage from verified USP",
  }),
  rule({
    id: "WB-RES-004",
    title: "Slides around USP",
    category: "research",
    priority: 82,
    appliesTo: ["wildberries", "research"],
    rule: "Дополнительные слайды строятся вокруг УТП.",
    decisionImpact: "slide narrative = USP proof chain",
  }),

  // ── Refinement ───────────────────────────────────────────────────────
  rule({
    id: "WB-REF-001",
    title: "Do not full regen winner",
    category: "refinement",
    priority: 75,
    appliesTo: ["wildberries", "refinement"],
    rule: "Не перегенерировать удачную карточку полностью.",
    decisionImpact: "mode=refinement preserves layout",
  }),
  rule({
    id: "WB-REF-002",
    title: "Change only necessary",
    category: "refinement",
    priority: 76,
    appliesTo: ["wildberries", "refinement"],
    rule: "Менять только необходимые элементы.",
    decisionImpact: "minimal delta on refinement",
  }),
  rule({
    id: "WB-REF-003",
    title: "Keep best version",
    category: "refinement",
    priority: 74,
    appliesTo: ["wildberries", "refinement"],
    rule: "Хранить лучшую версию.",
    decisionImpact: "version retention on refinement",
  }),
  rule({
    id: "WB-REF-004",
    title: "Rule of One Change",
    category: "refinement",
    priority: 78,
    appliesTo: ["wildberries", "refinement"],
    rule: "Rule of One Change — одно изменение за итерацию.",
    decisionImpact: "single-variable refinement",
  }),

  // ── Anti-rules ───────────────────────────────────────────────────────
  rule({
    id: "WB-ANTI-001",
    title: "No Hero overload",
    category: "anti_rule",
    priority: 100,
    appliesTo: ["wildberries", "anti_rule"],
    rule: "Не перегружать Hero.",
    decisionImpact: "block cluttered layouts",
  }),
  rule({
    id: "WB-ANTI-002",
    title: "No collage",
    category: "anti_rule",
    priority: 99,
    appliesTo: ["wildberries", "anti_rule"],
    rule: "Не делать collage.",
    decisionImpact: "reject multi-photo collage hero",
  }),
  rule({
    id: "WB-ANTI-003",
    title: "No competing background",
    category: "anti_rule",
    priority: 98,
    appliesTo: ["wildberries", "anti_rule"],
    rule: "Не использовать фон, конкурирующий с товаром.",
    decisionImpact: "backgroundContrastDirection enforced",
  }),
  rule({
    id: "WB-ANTI-004",
    title: "No text over product",
    category: "anti_rule",
    priority: 97,
    appliesTo: ["wildberries", "anti_rule"],
    rule: "Не делать текст поверх товара.",
    decisionImpact: "text in safe zones only",
  }),
  rule({
    id: "WB-ANTI-005",
    title: "No AI product if cutout exists",
    category: "anti_rule",
    priority: 96,
    appliesTo: ["wildberries", "anti_rule"],
    rule: "Не генерировать сам товар AI, если есть реальный cutout.",
    decisionImpact: "use real product cutout",
  }),
  rule({
    id: "WB-ANTI-006",
    title: "No one layout for all",
    category: "anti_rule",
    priority: 95,
    appliesTo: ["wildberries", "anti_rule"],
    rule: "Не использовать один layout для всех категорий.",
    decisionImpact: "category-aware layout",
  }),
];
