export {
  RENDER_BLUEPRINT_VERSION,
  type RenderBlueprint,
  type RenderBlueprintInput,
  type FluxAdapterOutput,
  type BlueprintSection,
  type MetaBlueprint,
  type CreativeBlueprint,
  type StoryBlueprint,
  type ProductBlueprint,
  type SceneBlueprint,
  type PhotographyBlueprint,
  type CameraBlueprint,
  type LightingBlueprint,
  type MaterialBlueprint,
  type CompositionBlueprint,
  type BackgroundBlueprint,
  type RenderBlueprintSettings,
  type ConstraintBlueprint,
  type ConstraintSet,
  type ValidationBlueprint,
  type SceneEnvironmentId,
} from "./types";

export {
  COVER_CONCEPT_TO_ENVIRONMENT,
  environmentFromCoverConcept,
  coverConceptFromEnvironment,
} from "./environment";

export { AGENT_WRITE_PERMISSIONS, agentMayWriteSection } from "./ownership";

export {
  CONSTITUTION_V18_VERSION,
  CONSTITUTION_V18_RULES,
  BANNED_AGENT_TOKENS,
  BANNED_PHOTOGRAPHY_MOOD,
  ConstitutionV18Error,
  assertAgentMayWriteSection,
  assertAgentOutputsClean,
  assertSingleEnvironmentSource,
  assertNoPromptStored,
  assertReadyForAdapter,
  assertPhotographyMoodClean,
} from "./constitution";

export { applyAgentPatch, type AgentPatch, type SectionPayloadMap } from "./patch";

export {
  createEmptyRenderBlueprint,
  renderBlueprintFromVisualPipeline,
  renderBlueprintToVisualSceneBlueprint,
} from "./from-visual-blueprint";

export {
  BlueprintLifecycle,
  SectionState,
  type BlueprintLifecycleMeta,
  type LifecycleStageSnapshot,
  type LifecycleManagedSection,
  type RollbackResult,
} from "./lifecycle-types";

export {
  BlueprintLockedError,
  LifecycleTransitionError,
  DEPENDENCY_CHILDREN,
  STAGE_EDITABLE_SECTIONS,
  createInitialLifecycleMeta,
  isLifecycleFrozen,
  assertSectionWritable,
  canTransitionSectionState,
  propagateDirty,
  markSectionDirtyAfterPatch,
  createLifecycleSnapshot,
  advanceLifecycleStage,
  rollbackToSnapshot,
  advanceToRendering,
  advancePostRenderStage,
} from "./lifecycle";

export {
  SECTION_VALIDATORS,
  STAGE_LOCK_SECTIONS,
  type SectionValidationResult,
} from "./section-validators";

export {
  type AgentContractId,
  type AgentError,
  type AgentErrorKind,
  type AgentResultBase,
  type AgentSectionUpdates,
  type BlueprintAgent,
  type BlueprintMutationResult,
  type RetryAdvice,
  AgentContractError,
  assertAgentConfidence,
} from "./agent-contracts";

export {
  AGENT_READ_MATRIX,
  AGENT_WRITE_MATRIX,
  AGENT_STAGE_MATRIX,
  agentMayReadSection,
  agentMayWriteSectionContract,
} from "./agent-matrix";

export { LifecycleManager, RetryLimitExceededError } from "./lifecycle-manager";

export {
  PipelineState,
  LifecycleEventType,
  RetryKind,
  DEFAULT_RETRY_LIMITS,
  type PipelineStateId,
  type LifecycleEvent,
  type LifecycleEventTypeId,
  type RetryKindId,
  type RetryLimits,
  type StagePrecondition,
  type DecisionNodeSnapshot,
  type StageSnapshot,
  type LifecycleLogEntry,
  type StageExecutionResult,
} from "./lifecycle-manager-types";

export { MutationEngine, MutationEngineError } from "./mutation-engine";
export type {
  BlueprintMutation,
  MutationBatch,
  MutationAppliedEvent,
  MutationAuditEntry,
  MutationApplyResult,
  MutationBatchResult,
} from "./mutation-types";
export { hashSection, hashValue } from "./section-hash";
export { validateMutation, validateBatchConflicts } from "./mutation-validators";

export {
  ValidationEngine,
  ValidationLevel,
  DEFAULT_VALIDATION_RULES,
  VAL_001_BLUEPRINT_STRUCTURE,
  VAL_002_LIFECYCLE,
  VAL_003_DEPENDENCIES,
  VAL_004_CAMERA,
  VAL_005_LIGHTING,
  VAL_006_COMPOSITION,
  VAL_007_BACKGROUND,
  VAL_008_PROFESSIONAL_LAYOUT,
  VAL_009_MARKETPLACE,
  VAL_010_ARCHITECTURE_INVARIANTS,
  VAL_BUSINESS_SCENE_LOGIC,
  type ValidationError,
  type ValidationResult,
  type ValidationRule,
  type ValidationReport,
  type ValidationSeverity,
  type ValidationWarning,
  type ValidationRuleCategory,
  type ValidationEngineOptions,
} from "./validation-engine";

export {
  ConstraintEngine,
  ConstraintEngineError,
  ConstraintCategory,
  ConstraintPriority,
  ConstraintSource,
  ResolutionStrategy,
  SOURCE_RESOLUTION_ORDER,
  DEFAULT_CONSTRAINT_PROVIDERS,
  SAFETY_CONSTRAINT_PROVIDER,
  MARKETPLACE_CONSTRAINT_PROVIDER,
  CREATIVE_CONSTRAINT_PROVIDER,
  STORY_CONSTRAINT_PROVIDER,
  COMPOSITION_CONSTRAINT_PROVIDER,
  GOVERNANCE_CONSTRAINT_PROVIDER,
  PROVIDER_FLUX_CONSTRAINT_PROVIDER,
  ARCHITECTURE_CONSTRAINT_PROVIDER,
  userConstraintsFromFlags,
  constraintsForProviderCapability,
  type Constraint,
  type ConstraintSet,
  type ConstraintConflict,
  type ConstraintReport,
  type ConstraintProvider,
  type ConstraintEngineOptions,
  type ConstraintPayload,
  type ConstraintCategoryId,
  type ResolutionStrategyId,
} from "./constraint-engine";

export {
  RollbackStrategy,
  RecoveryEventType,
  DEFAULT_MAX_RECOVERY_ATTEMPTS,
  DEFAULT_SNAPSHOT_RETENTION,
  type BlueprintSnapshot,
  type SnapshotMetadata,
  type SnapshotDelta,
  type SnapshotComparison,
  type RecoveryEvent,
  type RecoveryResult,
  type SnapshotRecoveryOptions,
  type SnapshotRetentionPolicy,
  type LifecycleStageSnapshot,
} from "./snapshot-types";
export {
  SnapshotManager,
  SnapshotIntegrityError,
  RecoveryLimitExceededError,
  validationResultFromReport,
  type StageSnapshot,
} from "./snapshot-manager";

export {
  EventBus,
  EventBusError,
  DesignEventType,
  EventCategory,
  EVENT_TYPE_CATEGORY,
  LIFECYCLE_TO_DESIGN_EVENT,
  lifecycleEventToPublish,
  mutationEventPayload,
  validationEventPayload,
  type DesignEvent,
  type DesignEventPayload,
  type DesignEventTypeId,
  type EventCategoryId,
  type EventMetadata,
  type EventHandler,
  type EventSubscription,
  type EventBusOptions,
  type EventReplayResult,
  type PublishInput,
} from "./event-bus";
export { RetryEngine, RetryLimitExceededError as RetryEngineLimitError } from "./retry-engine";
export {
  AgentRegistry,
  AgentRegistryError,
  createDefaultAgentRegistry,
  defaultAgentRegistry,
  descriptorFromAgent,
  registrationFromAgent,
  AgentType,
  AgentStatus,
  RegistryEventType,
  AGENT_REGISTRY_VERSION,
  AGENT_REGISTRY_GOLDEN_RULE,
  AGENT_CAPABILITY_TAGS,
  capabilityTagsForAgent,
  validateAgentRegistry,
  assertAgentRegistryValid,
  DEFAULT_DIRECTOR_CAPABILITIES,
  DEFAULT_CRITIC_CAPABILITIES,
  DEFAULT_ADAPTER_CAPABILITIES,
  type AgentDescriptor,
  type AgentCapabilities,
  type AgentMetadata,
  type AgentFactory,
  type AgentRegistration,
  type AgentInstanceRecord,
  type RegistryHealthIssue,
  type RegistryHealthResult,
  type RegistryAgentReport,
  type RegistryReport,
  type RegistryRuntimeOptions,
  type RegistryEvent,
  type RegistryEventTypeId,
  type AgentStatusId,
  type RegistryValidationResult,
} from "./agent-registry";
export { STAGE_PRECONDITIONS, assertStagePreconditions } from "./stage-preconditions";
export { canRunAgentsParallel, groupParallelAgents } from "./parallel-execution";

export {
  DecisionGraph,
  DecisionGraphError,
  DecisionType,
  DependencyKind,
  DEFAULT_DECISION_EDGES,
  DECISION_EXECUTION_ORDER,
  DECISION_NODE_ID,
  DECISION_PRODUCERS,
  agentIdToProducer,
  type DecisionConflict,
  type DecisionEdge,
  type DecisionNode,
  type DecisionProducerId,
  type DecisionTypeId,
  type DependencyKindId,
  type GraphValidationIssue,
  type GraphValidationResult,
  type InvalidationResult,
} from "./decision-graph";

export { storyDirectorAgent, universalStoryDirectorAgent, type StoryDirectorInput, type StoryDirectorResult } from "./agents/story-director-agent";

export {
  compileFluxAdapterOutput,
  RenderPipeline,
  defaultRenderPipeline,
  extractRenderIntent,
  negotiateCapabilities,
  compileNegativePrompt,
  validateCompiledPrompt,
  validateNegativePrompt,
  compilePromptForProvider,
  getProviderCapabilities,
} from "./render-pipeline";
export {
  RenderPipelineError,
  FluxRenderAdapter,
  GptImageRenderAdapter,
  SdxlRenderAdapter,
  PollinationsRenderAdapter,
  createDefaultAdapters,
  frozenTestBlueprint,
} from "./render-adapters";
export type {
  RenderIntent,
  ProviderRequest,
  ProviderResponse,
  ProviderMetadata,
  ProviderCapabilities,
  ProviderId,
  RenderAdapter,
  CompiledProviderRequest,
  ProviderRenderFn,
  RenderPipelineOptions,
  RenderPipelineResult,
  NegotiatedFields,
} from "./render-pipeline-types";
export { DEFAULT_FALLBACK_CHAIN } from "./render-pipeline-types";

export {
  SerializationError,
  serializeBlueprint,
  deserializeBlueprint,
  validateSerializable,
  computeBlueprintChecksum,
  exportBlueprintToJson,
  importBlueprintFromJson,
  assertSerializationRoundTrip,
  canonicalStringify,
  canonicalize,
  canonicalParse,
  migrateBlueprint,
  extractUnknownBlueprintFields,
  mergeUnknownBlueprintFields,
  runMigrationChain,
  BLUEPRINT_MIGRATION_CHAIN,
  SERIALIZATION_SCHEMA_VERSION,
  COMPRESSION_THRESHOLD_BYTES,
  type SerializableBlueprint,
  type SerializationMetadata,
  type SerializationFormat,
  type SerializationValidationIssue,
  type SerializationValidationResult,
  type SerializeOptions,
  type DeserializeOptions,
  type SerializedPayload,
  type ImageReference,
} from "./serialization";

export {
  CURRENT_BLUEPRINT_SCHEMA,
  CURRENT_PIPELINE_VERSION,
  parseBlueprintVersion,
  formatBlueprintVersion,
  compareBlueprintVersions,
  readBlueprintSchemaVersion,
  writeBlueprintSchemaVersion,
  evaluateCompatibility,
  compatibilityMessage,
  isUpgradeOnly,
} from "./blueprint-version";

export {
  CompatibilityStatus,
  type BlueprintVersion,
  type BlueprintMigration,
  type VersionManifest,
  type CompatibilityCheck,
  type MigrationStep,
  type MigrationResult,
  type VersionReport,
  type CompatibilityValidationResult,
  type SnapshotVersionRecord,
  type CompatibilityStatusId,
} from "./blueprint-version-types";

export {
  VersionEngineError,
  DEFAULT_ADAPTER_VERSION,
  buildVersionManifest,
  buildVersionManifestFromRegistry,
  createVersionReport,
  validateCompatibility,
  prepareBlueprintForPipeline,
  assertPipelineCompatible,
} from "./version-engine";

export {
  PerformanceTracker,
  PerformanceCache,
  PipelineQueue,
  PipelineContextPool,
  runWithAgentCache,
  planIncrementalRebuild,
  reuseUnchangedSections,
  shouldRunLazyStage,
  assertAsyncOperation,
  assertWithinLimits,
  buildAgentCacheKey,
  hashAgentInput,
  STAGE_TIME_BUDGET_MS,
  PERFORMANCE_PARALLEL_GROUPS,
  PERFORMANCE_SEQUENTIAL_CHAIN,
  STORY_SCENE_PHOTOGRAPHY_CHAIN,
  stageBudgetFor,
  isOverBudget,
  CacheLevel,
  PerformanceLayer,
  DEFAULT_PERFORMANCE_LIMITS,
  DEFAULT_STAGE_TIME_BUDGET_MS,
  type PerformanceLimits,
  type PerformanceMetrics,
  type StageTiming,
  type BottleneckReport,
  type IncrementalRebuildPlan,
  type AgentCacheKey,
  type CacheEntry,
  type LazyGateResult,
  type PipelineContextId,
  type PipelineQueueJob,
  type ParallelExecutionGroup,
} from "./performance-model";

export {
  ObservabilityEngine,
  ObservabilityError,
  attachObservabilityToEventBus,
  createDiagnosticContext,
  DiagnosticLevel,
  ErrorCategory,
  ObservabilityLayer,
  maskSecrets,
  sanitizeDiagnosticData,
  stripDebugOnlyFields,
  type DiagnosticContext,
  type DecisionTrace,
  type MutationTrace,
  type ValidationTrace,
  type AgentDiagnostic,
  type RenderDiagnostic,
  type CompositeDiagnostic,
  type VisionDiagnostic,
  type RetryDiagnostic,
  type TimelineEntry,
  type DiagnosticMetrics,
  type ExplainabilityReport,
  type FailureReport,
  type DiagnosticRecord,
  type ObservabilityMode,
  type ObservabilityOptions,
} from "./observability-engine";

export {
  RecoveryEngine,
  RecoveryEngineError,
  NonRecoverableError,
  classifyError,
  isNonRecoverable,
  strategyForSeverity,
  planVisionRecovery,
  planProviderRecovery,
  providerRecoveryToPlan,
  rollbackStrategyForRecovery,
  escalateStrategy,
  assertRecoveryInvariants,
  assertRecoveryInvariantsOrThrow,
  validateAgentRecommendation,
  RECOVERY_ESCALATION_CHAIN,
  RecoveryErrorCategory,
  ErrorSeverity,
  RecoveryStrategy,
  DEFAULT_RETRY_POLICY,
  type RecoveryErrorCategoryId,
  type ErrorSeverityId,
  type RecoveryStrategyId,
  type RetryPolicy,
  type RecoveryRecommendation,
  type ClassifiedError,
  type RecoveryPlan,
  type RecoveryLog,
  type RecoveryMetrics,
  type ProviderRecoveryAction,
  type VisionProblemId,
  type RecoveryInvariantViolation,
} from "./recovery-engine";

export {
  TestCategory,
  TEST_PYRAMID_ORDER,
  COVERAGE_TARGETS,
  RELEASE_QUALITY_GATES,
  GOLDEN_DATASET,
  V18_TEST_REGISTRY,
  specsForCategory,
  specsWithoutLlm,
  prRequiredCategories,
  MockLLMProvider,
  deterministicMockKey,
  RegressionStore,
  captureBlueprintBaseline,
  TestingArchitectureError,
  runSpecFile,
  runCategory,
  runPullRequestSuite,
  runReleaseCandidateSuite,
  assertQualityGate,
  formatTestReport,
  buildDeterministicContext,
  assertDeterministic,
  simulateStressConcurrency,
  STRESS_LEVELS,
  runAllChaosScenarios,
  assertChaosRecoveryOrThrow,
  testBlueprintAgentContract,
  testRenderAdapterContract,
  detectVisionIssues,
  visionScoreFromBlueprint,
  type TestCategoryId,
  type TestRunReport,
  type GoldenProduct,
  type RegressionComparison,
  type ContractTestResult,
  type VisionIssue,
} from "./testing-architecture";

export {
  VisionQA,
  VisionQAError,
  defaultVisionQA,
  analyzeVision,
  VisionCategory,
  IssueSeverity,
  VISION_THRESHOLDS,
  VISION_METRIC_WEIGHTS,
  deriveVisionSignals,
  hashVisionImage,
  analyzeVisionSignals,
  passesVisionThresholds,
  recommendationsFromIssues,
  VisionHistoryStore,
  type VisionInput,
  type VisionReport,
  type VisionMetrics,
  type VisionQAIssue,
  type VisionRecommendation,
  type VisionCategoryId,
  type IssueSeverityId as VisionIssueSeverityId,
  type VisionImageSignals,
  type VisionHistoryEntry,
  type BoundingBox,
} from "./vision-qa-engine";

export {
  ARCHITECTURAL_INVARIANTS_VERSION,
  ARCHITECTURAL_INVARIANTS,
  ARCHITECTURAL_INVARIANT_IDS,
  ArchitecturalInvariantId,
  getInvariantDefinition,
  invariantByName,
  type ArchitecturalInvariantDefinition,
  type ArchitecturalInvariantIdValue,
  type ArchitecturalInvariantSeverity,
  type ArchitecturalInvariantViolation,
  type ArchitectureValidationContext,
  type ArchitectureValidationReport,
  type ArchitectureValidatorOptions,
} from "./architectural-invariants";

export {
  ArchitectureValidator,
  ArchitectureValidatorError,
  validateArchitecture,
  assertArchitectureInvariants,
  validateArchitectureAtPipelineStart,
  assertPipelineArchitecture,
  validateRecoveryArchitecture,
} from "./architecture-validator";

export {
  AGENT_ECOSYSTEM_VERSION,
  AGENT_ECOSYSTEM_GOLDEN_RULE,
  AGENT_PRINCIPLES,
  AGENT_PRINCIPLE_IDS,
  AGENT_CATEGORIES,
  AGENT_CATEGORY_MAP,
  AgentPrinciple,
  AgentEcosystemCategory,
  getAgentCategory,
  agentsInCategory,
  getPrincipleDefinition,
  getCategoryDefinition,
  isDesignAgent,
  type AgentPrincipleId,
  type AgentEcosystemCategoryId,
  type AgentPrincipleDefinition,
  type AgentCategoryDefinition,
  type AgentEcosystemViolation,
  type AgentDecisionRecord,
  type AgentEcosystemValidationReport,
  type AgentEcosystemValidationContext,
  type AgentEcosystemValidatorOptions,
} from "./agent-ecosystem";

export {
  AgentEcosystemValidator,
  AgentEcosystemError,
  validateAgentEcosystem,
  assertAgentEcosystem,
  recordAgentDecision,
} from "./agent-ecosystem-validator";

export {
  UNIVERSAL_AGENT_CONTRACT_VERSION,
  UNIVERSAL_AGENT_CONTRACT_GOLDEN_RULE,
  STABLE_AGENT_IDS,
  AgentCategory,
  categoryForAgent,
  consumesForAgent,
  producesForAgent,
  normalizeConfidence,
  denormalizeConfidence,
  createAgentContext,
  preconditionsMet,
  type AgentCategoryId,
  type AgentContext,
  type AgentRecommendation,
  type AgentDiagnostics,
  type UniversalAgentResult,
  type UniversalBlueprintAgent,
  type PipelineConfig,
  type UniversalContractViolation,
  type UniversalContractReport,
  type LegacyAgentAdapterOptions,
  type StableAgentId,
} from "./universal-agent-contract";

export {
  wrapLegacyBlueprintAgent,
  updatesToMutations,
  buildAgentDiagnostics,
  legacyResultToUniversal,
  universalToLegacyConfidence,
} from "./universal-agent-bridge";

export {
  UniversalAgentContractValidator,
  UniversalContractError,
  validateUniversalAgentInterface,
  validateUniversalAgentResult,
  validateUniversalAgentContract,
  assertUniversalAgentContract,
  assertNoForbiddenSideEffects,
} from "./universal-agent-contract-validator";

export {
  AGENT_LIFECYCLE_VERSION,
  AGENT_LIFECYCLE_GOLDEN_RULE,
  AGENT_LIFECYCLE_STAGE_ORDER,
  AGENT_LIFECYCLE_GUARANTEES,
  AgentLifecycleStage,
  assertStageOrder,
  nextLifecycleStage,
  type AgentLifecycleStageId,
  type AgentLifecycleStageRecord,
  type AgentLifecycleFailure,
  type AgentLifecycleResult,
  type AgentLifecycleRunInput,
  type AgentLifecycleOrchestratorOptions,
  type AgentLifecycleGuarantee,
} from "./agent-lifecycle";

export {
  AgentLifecycleOrchestrator,
  AgentLifecycleSession,
  AgentLifecycleError,
  runAgentLifecycle,
} from "./agent-lifecycle-orchestrator";

export {
  AGENT_DISCOVERY_VERSION,
  AGENT_DISCOVERY_GOLDEN_RULE,
  PipelineMode,
  MARKETPLACE_AGENT_CHAIN,
  MODE_SKIP_AGENTS,
  agentsForLifecycleStage,
  isAgentSkippedByMode,
  defaultPipelineConfiguration,
  type PipelineModeId,
  type PipelineConfiguration,
  type DiscoveryContext,
  type ExecutionNode,
  type ExecutionEdge,
  type ExecutionGroup,
  type ExecutionPlan,
  type DiscoveryExclusion,
  type DiscoveryExclusionCode,
  type DiscoveryReport,
} from "./agent-discovery";

export {
  AgentDiscoveryEngine,
  AgentDiscoveryError,
  discoverAgents,
} from "./agent-discovery-engine";

export {
  AGENT_DEPENDENCY_VERSION,
  AGENT_DEPENDENCY_GOLDEN_RULE,
  DEFAULT_SECTION_CHAIN,
  buildSectionDependencyEdges,
  detectSectionCycle,
  topologicalSortSections,
  downstreamSections,
  exportDependencyGraph,
  getAgentDependency,
  getAllAgentDependencies,
  getSectionOwner,
  validateOwnership,
  validateAgentDependencies,
  validateDependencyGraph,
  propagateSectionChange,
  buildExecutionPlanFromDependencies,
  agentsUnaffectedBySectionChange,
  type AgentDependency,
  type ConditionalDependency,
  type DependencyRequirement,
  type DependencyRequirementId,
  type DependencyValidationContext,
  type DependencyValidationReport,
  type DependencyViolation,
  type DependencyPropagationResult,
  type DependencyGraphExport,
  type SectionDependencyEdge,
} from "./agent-dependency-engine";

export {
  AGENT_CONTEXT_VERSION,
  AGENT_CONTEXT_GOLDEN_RULE,
  buildAgentContextPackage,
  bridgePipelineConfig,
  validateAgentContextPackage,
  scanContextSecurity,
  projectAgentContext,
  explainContextUsage,
  serializeAgentContext,
  deserializeAgentContext,
  detectContextMutation,
  type AgentContextPackage,
  type AgentContextBuildInput,
  type AgentDiagnosticContext,
  type RuntimeContext,
  type ContextValidationReport,
  type ContextViolation,
  type ContextProjection,
  type ContextExplainabilityReport,
  type ContextExplainabilityEntry,
  type SerializedAgentContext,
  type ContextViolationCode,
} from "./agent-context-engine";

export const USE_RENDER_BLUEPRINT_V18 = process.env.RENDER_BLUEPRINT_V18 === "1";
