/**
 * Chapter 7.13 — Photography Director Agent engine.
 * Designs commercial photography style — never composition layout or final lighting math.
 */
import type { AgentContractId } from "./agent-contracts";
import { buildAgentContextPackage } from "./agent-context-engine";
import { buildAgentMemoryPackage, releaseAgentMemory } from "./agent-memory-engine";
import { executeProfessionalDecision } from "./agent-professional-decision-engine";
import { COMMERCIAL_PHOTO_DIRECTOR_ID } from "./commercial-photo-director-engine";
import {
  fromPlannedCompositionBlueprint,
  toCompositionPlanningInput,
  toPlannedCompositionFromAgentBlueprint,
  toPlannedSceneFromAgentBlueprint,
  buildBatterySprayerCompositionDirectorInput,
} from "./composition-director-agent-engine";
import { runCompositionPlanningStage } from "./composition-planning-stage-engine";
import { createEmptyRenderBlueprint } from "./from-visual-blueprint";
import {
  CameraPreset,
  LensPreset,
  PlannedPhotographyStyle,
  runPhotographyPlanningStage,
  selectPhotographyStyle,
  type PhotographyPlanningContext,
  type PhotographyPlanningInput,
  type PhotographyPlanningSection,
  type PlannedPhotographyBlueprint,
  type PlannedPhotographyStyleId,
} from "./photography-planning-stage-engine";
import { toPlannedStoryFromAgentBlueprint } from "./scene-director-agent-engine";
import { SceneCategory } from "./scene-planning-stage-types";
import {
  PHOTOGRAPHY_DIRECTOR_AGENT_ID,
  PhotographyDirectorAgentModule,
  type PhotographyDirectorAgentBlueprint,
  type PhotographyDirectorAgentContext,
  type PhotographyDirectorAgentExecutionReport,
  type PhotographyDirectorAgentFailureCode,
  type PhotographyDirectorAgentInput,
  type PhotographyDirectorAgentKpi,
  type PhotographyDirectorAgentModuleDefinition,
  type PhotographyDirectorAgentModuleId,
  type PhotographyDirectorAgentModuleRecord,
  type PhotographyDirectorAgentPipelineLink,
  type PhotographyDirectorAgentRetryBranch,
  type PhotographyDirectorAgentValidationReport,
  type PhotographyDirectorAgentViolation,
} from "./photography-director-agent-types";

export {
  PHOTOGRAPHY_DIRECTOR_AGENT_ID,
  PhotographyDirectorAgentModule,
  type PhotographyDirectorAgentModuleId,
  type PhotographyDirectorAgentInput,
  type PhotographyDirectorAgentBlueprint,
  type PhotographyDirectorAgentModuleRecord,
  type PhotographyDirectorAgentKpi,
  type PhotographyDirectorAgentViolation,
  type PhotographyDirectorAgentRetryBranch,
  type PhotographyDirectorAgentExecutionReport,
  type PhotographyDirectorAgentValidationReport,
  type PhotographyDirectorAgentContext,
  type PhotographyDirectorAgentFailureCode,
  type PhotographyDirectorAgentModuleDefinition,
  type PhotographyDirectorAgentPipelineLink,
} from "./photography-director-agent-types";

export const PHOTOGRAPHY_DIRECTOR_AGENT_VERSION = "7.13.0";

export const PHOTOGRAPHY_DIRECTOR_AGENT_GOLDEN_RULE =
  "The buyer must believe the product truly exists in front of them — not that the image was " +
  "generated by AI. Photography Director does not choose the scene, build composition, or control " +
  "light — it makes prior agent work look like professional commercial photography that builds trust.";

export const PHOTOGRAPHY_DIRECTOR_AGENT_MISSION =
  'Answer: "How should this be photographed to look like professional commercial photography?" — ' +
  "realistic, trustworthy, quality-emphasizing, marketplace-appropriate product photography.";

export const PHOTOGRAPHY_DIRECTOR_AGENT_MODULES: readonly PhotographyDirectorAgentModuleDefinition[] = [
  { id: PhotographyDirectorAgentModule.PHOTOGRAPHY_STYLE_SELECTOR, order: 1, label: "Photography Style Selector", responsibility: "Select commercial photo style by category" },
  { id: PhotographyDirectorAgentModule.COMMERCIAL_SHOOTING_ENGINE, order: 2, label: "Commercial Shooting Engine", responsibility: "Define shooting type that reinforces Story" },
  { id: PhotographyDirectorAgentModule.PERSPECTIVE_PLANNER, order: 3, label: "Perspective Planner", responsibility: "Choose credible product perspective" },
  { id: PhotographyDirectorAgentModule.DEPTH_OF_FIELD_PLANNER, order: 4, label: "Depth Of Field Planner", responsibility: "Focus attention on Hero Product" },
  { id: PhotographyDirectorAgentModule.REALISM_CONTROLLER, order: 5, label: "Realism Controller", responsibility: "Eliminate AI-artificial appearance" },
  { id: PhotographyDirectorAgentModule.PHOTOGRAPHY_VALIDATOR, order: 6, label: "Photography Validator", responsibility: "Validate story alignment and hero dominance" },
  { id: PhotographyDirectorAgentModule.PHOTOGRAPHY_BLUEPRINT_BUILDER, order: 7, label: "Photography Blueprint Builder", responsibility: "Assemble Photography Blueprint for Pipeline Context" },
] as const;

export const PHOTOGRAPHY_DIRECTOR_AGENT_PIPELINE: readonly PhotographyDirectorAgentPipelineLink[] = [
  { from: "composition_director", to: "photography_director" },
  { from: "photography_director", to: "lighting_director" },
] as const;

const CONFIDENCE_THRESHOLD = 0.75;
const REALISM_MIN_SCORE = 0.7;

const PHOTO_STYLE_LABELS: Record<string, string> = {
  [PlannedPhotographyStyle.STUDIO_COMMERCIAL]: "Studio Commercial",
  [PlannedPhotographyStyle.PREMIUM_LIFESTYLE]: "Premium Product Photography",
  [PlannedPhotographyStyle.EDITORIAL_PRODUCT]: "Lifestyle Photography",
  [PlannedPhotographyStyle.TECHNICAL_CATALOG]: "Industrial Photography",
  [PlannedPhotographyStyle.MINIMAL_PRODUCT]: "Minimal Premium",
  [PlannedPhotographyStyle.MODERN_MARKETPLACE]: "Outdoor Commercial",
};

const PERSPECTIVE_LABELS: Record<string, string> = {
  three_quarter: "Three Quarter View",
  eye_level_three_quarter: "Eye Level",
  front: "Hero Perspective",
  top_down: "Top Angle",
  slight_low: "Slight Low Angle",
};

const DEPTH_LABELS: Record<string, string> = {
  medium_product_sharp: "Hero sharp, background softly blurred",
  moderate_background_blur: "Product sharp with gentle background falloff",
  deep_sharp_throughout: "Deep focus across product details",
  extreme_background_blur: "Extreme background blur",
};

const LENS_LABELS: Record<string, string> = {
  [LensPreset.LENS_35MM]: "35mm commercial lifestyle",
  [LensPreset.LENS_50MM]: "50mm natural perspective",
  [LensPreset.LENS_85MM]: "85mm premium product",
  [LensPreset.LENS_100MM_MACRO]: "100mm macro detail",
};

const COMPOSITION_KEYWORDS =
  /\b(hero area|headline area|badge layout|safe zone|layout pattern|white space ratio)\b/i;

function violation(
  code: PhotographyDirectorAgentFailureCode,
  message: string,
  module?: PhotographyDirectorAgentModuleId,
): PhotographyDirectorAgentViolation {
  return { code, message, module };
}

function recordModule(
  records: PhotographyDirectorAgentModuleRecord[],
  completed: PhotographyDirectorAgentModuleId[],
  module: PhotographyDirectorAgentModuleId,
  detail?: string,
): void {
  completed.push(module);
  records.push({ module, at: Date.now(), detail });
}

function isGardenProduct(profile: PhotographyDirectorAgentInput["productProfile"]): boolean {
  const sub = profile.subcategory.toLowerCase();
  const cat = profile.category.toLowerCase();
  return sub.includes("sprayer") || cat.includes("garden");
}

export function formatPhotoStyleLabel(style: string): string {
  return PHOTO_STYLE_LABELS[style] ?? style.replace(/_/g, " ");
}

export function formatPerspectiveLabel(angle: string): string {
  return PERSPECTIVE_LABELS[angle] ?? angle.replace(/_/g, " ");
}

export function formatDepthOfFieldLabel(depth: string): string {
  return DEPTH_LABELS[depth] ?? depth.replace(/_/g, " ");
}

export function formatLensProfile(lens: string): string {
  return LENS_LABELS[lens] ?? lens;
}

export function deriveShootingType(
  planned: PlannedPhotographyBlueprint,
  input: PhotographyDirectorAgentInput,
): string {
  if (planned.cameraPreset === CameraPreset.TECHNICAL_DOCUMENTATION) {
    return "technical_documentation";
  }
  const scene = toPlannedSceneFromAgentBlueprint(input.sceneBlueprint);
  if (scene.sceneType === SceneCategory.OUTDOOR || isGardenProduct(input.productProfile)) {
    return "in_use_workflow";
  }
  if (planned.cameraPreset === CameraPreset.STUDIO_PRODUCT) {
    return "studio_product";
  }
  return "commercial_lifestyle";
}

export function deriveFraming(
  planned: PlannedPhotographyBlueprint,
  input: PhotographyDirectorAgentInput,
): string {
  const heroWidth = input.layoutBlueprint.heroPlacement.width;
  const heightLabel = planned.cameraHeight === "high" ? "elevated" : "eye_level";
  return `${heightLabel} framing, hero ${Math.round(heroWidth * 100)}% width, overlay reserve preserved`;
}

export function deriveRealismLevel(planned: PlannedPhotographyBlueprint): string {
  if (planned.shadowStyle === "harsh_artificial" || planned.lens === "unknown") return "low";
  if (planned.reflectionStyle.includes("impossible")) return "low";
  return "high";
}

export function computeRealismScore(planned: PlannedPhotographyBlueprint): number {
  if (planned.lens === "unknown" || planned.cameraPreset === "random_camera") return 0.3;
  if (planned.shadowStyle === "harsh_artificial") return 0.4;
  if (planned.depthOfField === "extreme_background_blur") return 0.55;
  if (planned.reflectionStyle.includes("soft_matte") || planned.reflectionStyle.includes("natural")) return 0.92;
  return 0.88;
}

export function fromPlannedPhotographyBlueprint(
  planned: PlannedPhotographyBlueprint,
  style: PlannedPhotographyStyleId,
  input: PhotographyDirectorAgentInput,
  confidence: number,
): PhotographyDirectorAgentBlueprint {
  return {
    photoStyle: formatPhotoStyleLabel(style),
    shootingType: deriveShootingType(planned, input),
    framing: deriveFraming(planned, input),
    perspective: formatPerspectiveLabel(planned.cameraAngle),
    depthOfField: formatDepthOfFieldLabel(planned.depthOfField),
    realismLevel: deriveRealismLevel(planned),
    commercialMood: input.storyBlueprint.emotionalDirection,
    lensProfile: formatLensProfile(planned.lens),
    confidence,
  };
}

export function validatePhotographyDirectorAgentBlueprint(
  blueprint?: PhotographyDirectorAgentBlueprint,
  input?: PhotographyDirectorAgentInput,
  planned?: PlannedPhotographyBlueprint,
): PhotographyDirectorAgentViolation[] {
  const violations: PhotographyDirectorAgentViolation[] = [];
  if (!blueprint) {
    violations.push(
      violation("BLUEPRINT_INCOMPLETE", "Photography Blueprint is required", PhotographyDirectorAgentModule.PHOTOGRAPHY_BLUEPRINT_BUILDER),
    );
    return violations;
  }

  if (/catalog/i.test(blueprint.shootingType) && input && isGardenProduct(input.productProfile)) {
    violations.push(
      violation("CATALOG_SHOOTING_MISMATCH", "Garden product must use in-use workflow, not catalog photography", PhotographyDirectorAgentModule.COMMERCIAL_SHOOTING_ENGINE),
    );
  }

  if (blueprint.realismLevel === "low") {
    violations.push(
      violation("ARTIFICIAL_PHOTOGRAPHY", "Photography must look professionally plausible", PhotographyDirectorAgentModule.REALISM_CONTROLLER),
    );
  }

  if (blueprint.perspective === "Top Angle" && input?.layoutBlueprint.layoutPattern.includes("Marketplace")) {
    violations.push(
      violation("PERSPECTIVE_COMPOSITION_CONFLICT", "Top angle conflicts with marketplace hero composition", PhotographyDirectorAgentModule.PERSPECTIVE_PLANNER),
    );
  }

  if (!blueprint.lensProfile || !blueprint.photoStyle) {
    violations.push(
      violation("RANDOM_CAMERA_PARAMS", "Lens and photo style must be story-driven", PhotographyDirectorAgentModule.PERSPECTIVE_PLANNER),
    );
  }

  if (planned && !planned.lightingPreset) {
    violations.push(
      violation("MISSING_LIGHTING_STRATEGY", "Lighting strategy must be defined before handoff", PhotographyDirectorAgentModule.PHOTOGRAPHY_VALIDATOR),
    );
  }

  if (planned?.depthOfField === "extreme_background_blur") {
    violations.push(
      violation("HERO_LOSES_ADVANTAGE", "Depth of field must keep hero product visually dominant", PhotographyDirectorAgentModule.DEPTH_OF_FIELD_PLANNER),
    );
  }

  const serialized = JSON.stringify(blueprint);
  if (COMPOSITION_KEYWORDS.test(serialized)) {
    violations.push(
      violation("CONTAINS_COMPOSITION_DECISION", "Photography must not decide composition layout", PhotographyDirectorAgentModule.PHOTOGRAPHY_VALIDATOR),
    );
  }

  const realism = planned ? computeRealismScore(planned) : blueprint.realismLevel === "high" ? 0.9 : 0.4;
  if (realism < REALISM_MIN_SCORE) {
    violations.push(
      violation("LOW_REALISM", "Realism score below acceptable threshold", PhotographyDirectorAgentModule.REALISM_CONTROLLER),
    );
  }

  return violations;
}

export function buildPhotographyDirectorAgentKpis(input: {
  blueprint: PhotographyDirectorAgentBlueprint;
  planned: PlannedPhotographyBlueprint;
  confidence: number;
  retryCount: number;
  planningValid: boolean;
  marketplaceAligned: boolean;
}): PhotographyDirectorAgentKpi {
  const { blueprint, planned, confidence, retryCount, planningValid, marketplaceAligned } = input;
  const realism = computeRealismScore(planned);
  return {
    realismScore: realism,
    commercialPhotographyScore: planningValid && blueprint.photoStyle ? 0.93 : 0.5,
    productTrustScore: blueprint.realismLevel === "high" ? 0.91 : 0.45,
    perspectiveQuality: blueprint.perspective.includes("Quarter") || blueprint.perspective.includes("Eye") ? 0.92 : 0.7,
    marketplaceFit: marketplaceAligned ? 0.9 : 0.65,
    heroVisibility: planned.depthOfField.includes("product_sharp") || planned.depthOfField.includes("moderate") ? 0.92 : 0.75,
    retryRate: retryCount > 0 ? retryCount / (retryCount + 1) : 0,
    confidenceScore: confidence,
  };
}

export function mapPhotographyDirectorModuleToPlanningStage(module: PhotographyDirectorAgentModuleId): string {
  const mapping: Record<PhotographyDirectorAgentModuleId, string> = {
    [PhotographyDirectorAgentModule.PHOTOGRAPHY_STYLE_SELECTOR]: "photography_style",
    [PhotographyDirectorAgentModule.COMMERCIAL_SHOOTING_ENGINE]: "camera_selection",
    [PhotographyDirectorAgentModule.PERSPECTIVE_PLANNER]: "camera_angle",
    [PhotographyDirectorAgentModule.DEPTH_OF_FIELD_PLANNER]: "depth_of_field",
    [PhotographyDirectorAgentModule.REALISM_CONTROLLER]: "physical_realism",
    [PhotographyDirectorAgentModule.PHOTOGRAPHY_VALIDATOR]: "validation",
    [PhotographyDirectorAgentModule.PHOTOGRAPHY_BLUEPRINT_BUILDER]: "blueprint_assembly",
  };
  return mapping[module];
}

export function toPhotographyPlanningInput(input: PhotographyDirectorAgentInput): PhotographyPlanningInput {
  return {
    profile: input.productProfile,
    story: toPlannedStoryFromAgentBlueprint(input.storyBlueprint),
    scene: toPlannedSceneFromAgentBlueprint(input.sceneBlueprint),
    composition: toPlannedCompositionFromAgentBlueprint(input.layoutBlueprint),
    knowledge: input.knowledgePackage,
    marketplace: input.productProfile.marketplace ?? "wildberries",
  };
}

export function buildDefaultPhotographyDirectorAgentInput(
  overrides: Partial<PhotographyDirectorAgentInput> = {},
): PhotographyDirectorAgentInput {
  const compositionInput = buildBatterySprayerCompositionDirectorInput();
  const compositionPlanning = runCompositionPlanningStage(toCompositionPlanningInput(compositionInput));
  const layoutBlueprint = fromPlannedCompositionBlueprint(
    compositionPlanning.section!.plannedBlueprint,
    compositionPlanning.section!.confidence,
  );

  return {
    productProfile: compositionInput.productProfile,
    businessModel: compositionInput.businessModel,
    storyBlueprint: compositionInput.storyBlueprint,
    sceneBlueprint: compositionInput.sceneBlueprint,
    layoutBlueprint,
    knowledgePackage: compositionInput.knowledgePackage,
    ...overrides,
  };
}

export function buildBatterySprayerPhotographyDirectorInput(): PhotographyDirectorAgentInput {
  return buildDefaultPhotographyDirectorAgentInput();
}

function toPlanningContext(context: PhotographyDirectorAgentContext): PhotographyPlanningContext {
  return {
    randomCameraParams: context.randomCameraParams,
    perspectiveCompositionConflict: context.perspectiveCompositionConflict,
    artificialPhotography: context.artificialPhotography,
    missingLightingStrategy: context.missingLightingStrategy,
    heroLosesAdvantage: context.heroLosesAdvantage,
  };
}

function resolveRetryBranch(context: PhotographyDirectorAgentContext): PhotographyDirectorAgentRetryBranch | undefined {
  if (context.skipRetry) return undefined;
  if (
    context.randomCameraParams ||
    context.perspectiveCompositionConflict ||
    context.artificialPhotography ||
    context.heroLosesAdvantage ||
    context.catalogShootingType ||
    context.lowConfidence
  ) {
    return "style_perspective_realism";
  }
  return undefined;
}

export async function executePhotographyDirectorAgent(input: {
  agentInput?: PhotographyDirectorAgentInput;
  context?: PhotographyDirectorAgentContext;
}): Promise<PhotographyDirectorAgentExecutionReport> {
  const started = Date.now();
  const context = input.context ?? {};
  const maxRetries = context.maxRetries ?? 1;
  const agentInput = input.agentInput ?? buildBatterySprayerPhotographyDirectorInput();
  const violations: PhotographyDirectorAgentViolation[] = [];
  const modulesCompleted: PhotographyDirectorAgentModuleId[] = [];
  const moduleRecords: PhotographyDirectorAgentModuleRecord[] = [];
  let retryCount = 0;
  let retryBranch: PhotographyDirectorAgentRetryBranch | undefined;

  const planningInput = toPhotographyPlanningInput(agentInput);
  const planningContext = toPlanningContext(context);

  let planningReport = runPhotographyPlanningStage(planningInput, planningContext);

  const recordPlanningModules = (section?: PhotographyPlanningSection, suffix = "") => {
    const planned = section?.plannedBlueprint;
    const style = section?.photographyStyle ?? selectPhotographyStyle(planningInput);
    recordModule(moduleRecords, modulesCompleted, PhotographyDirectorAgentModule.PHOTOGRAPHY_STYLE_SELECTOR, `${formatPhotoStyleLabel(style)}${suffix}`);
    recordModule(moduleRecords, modulesCompleted, PhotographyDirectorAgentModule.COMMERCIAL_SHOOTING_ENGINE, `${section?.cameraPreset ?? ""}${suffix}`);
    recordModule(moduleRecords, modulesCompleted, PhotographyDirectorAgentModule.PERSPECTIVE_PLANNER, `${planned?.cameraAngle ?? ""}${suffix}`);
    recordModule(moduleRecords, modulesCompleted, PhotographyDirectorAgentModule.DEPTH_OF_FIELD_PLANNER, `${planned?.depthOfField ?? ""}${suffix}`);
    recordModule(moduleRecords, modulesCompleted, PhotographyDirectorAgentModule.REALISM_CONTROLLER, `${planned?.reflectionStyle ?? ""}${suffix}`);
    recordModule(moduleRecords, modulesCompleted, PhotographyDirectorAgentModule.PHOTOGRAPHY_VALIDATOR, `${planningReport.violations.length} checks${suffix}`);
    recordModule(moduleRecords, modulesCompleted, PhotographyDirectorAgentModule.PHOTOGRAPHY_BLUEPRINT_BUILDER, "blueprint assembled" + suffix);
  };

  recordPlanningModules(planningReport.section);

  let blueprint = planningReport.section
    ? fromPlannedPhotographyBlueprint(
        planningReport.section.plannedBlueprint,
        planningReport.section.photographyStyle,
        agentInput,
        planningReport.section.confidence,
      )
    : undefined;

  let confidence = blueprint?.confidence ?? 0;
  if (context.lowConfidence) confidence = 0.55;

  if (context.catalogShootingType && blueprint) {
    blueprint = { ...blueprint, shootingType: "catalog_photography" };
  }

  for (const v of planningReport.violations) {
    violations.push(violation(v.code as PhotographyDirectorAgentFailureCode, v.message));
  }
  violations.push(
    ...validatePhotographyDirectorAgentBlueprint(
      blueprint,
      agentInput,
      planningReport.section?.plannedBlueprint,
    ),
  );

  while (retryCount < maxRetries && !context.skipRetry) {
    const branch = resolveRetryBranch(context);
    if (!branch || confidence >= CONFIDENCE_THRESHOLD) break;

    retryCount += 1;
    retryBranch = branch;

    const retryContext: PhotographyPlanningContext = {
      randomCameraParams: false,
      perspectiveCompositionConflict: false,
      artificialPhotography: false,
      missingLightingStrategy: false,
      heroLosesAdvantage: false,
    };

    planningReport = runPhotographyPlanningStage(planningInput, retryContext);
    blueprint = planningReport.section
      ? fromPlannedPhotographyBlueprint(
          planningReport.section.plannedBlueprint,
          planningReport.section.photographyStyle,
          agentInput,
          planningReport.section.confidence,
        )
      : blueprint;
    confidence = blueprint?.confidence ?? confidence;

    violations.length = 0;
    for (const v of planningReport.violations) {
      violations.push(violation(v.code as PhotographyDirectorAgentFailureCode, v.message));
    }
    violations.push(
      ...validatePhotographyDirectorAgentBlueprint(
        blueprint,
        agentInput,
        planningReport.section?.plannedBlueprint,
      ),
    );
    recordPlanningModules(planningReport.section, ` retry ${retryCount}`);
  }

  if (retryCount > 0 && planningReport.valid) {
    confidence = Math.max(confidence, CONFIDENCE_THRESHOLD);
  }

  if (context.artificialPhotography && retryCount >= maxRetries && !context.skipRetry && !planningReport.valid) {
    violations.push(violation("RETRY_EXHAUSTED", "Style selector and realism retry did not resolve artificial look"));
  }

  const bp = createEmptyRenderBlueprint({
    category: agentInput.productProfile.category,
    seed: 37,
  });
  const workingContext = buildAgentContextPackage({
    blueprint: bp,
    agentId: PHOTOGRAPHY_DIRECTOR_AGENT_ID,
  });
  const memoryPackage = buildAgentMemoryPackage({
    agentId: PHOTOGRAPHY_DIRECTOR_AGENT_ID,
    working: workingContext,
  });
  releaseAgentMemory(memoryPackage);

  const decision = await executeProfessionalDecision({
    agentId: PHOTOGRAPHY_DIRECTOR_AGENT_ID as AgentContractId,
    blueprint: bp,
  });
  if (!decision.valid) {
    violations.push(violation("EXECUTION_FAILED", "Professional decision must validate photography direction"));
  }
  if (!decision.state.problem?.professionalQuestion.toLowerCase().includes("professional")) {
    violations.push(violation("EXECUTION_FAILED", "Decision problem must be photography-focused"));
  }

  const marketplaceAligned =
    planningInput.marketplace === (agentInput.productProfile.marketplace ?? "wildberries");
  const durationMs = Date.now() - started;

  const kpis = buildPhotographyDirectorAgentKpis({
    blueprint: blueprint ?? {
      photoStyle: "",
      shootingType: "",
      framing: "",
      perspective: "",
      depthOfField: "",
      realismLevel: "",
      commercialMood: "",
      lensProfile: "",
      confidence: 0,
    },
    planned: planningReport.section?.plannedBlueprint ?? {
      cameraPreset: "",
      lens: "",
      cameraAngle: "",
      cameraHeight: "",
      depthOfField: "",
      lightingPreset: "",
      exposure: "",
      whiteBalance: "",
      shadowStyle: "",
      reflectionStyle: "",
    },
    confidence,
    retryCount,
    planningValid: planningReport.valid,
    marketplaceAligned,
  });

  const uniqueViolations = dedupeViolations(violations);
  const modulesComplete =
    modulesCompleted.length >= PHOTOGRAPHY_DIRECTOR_AGENT_MODULES.length ||
    PHOTOGRAPHY_DIRECTOR_AGENT_MODULES.every((m) => modulesCompleted.includes(m.id));

  return {
    valid: uniqueViolations.length === 0 && planningReport.valid && modulesComplete && Boolean(blueprint),
    agentId: PHOTOGRAPHY_DIRECTOR_AGENT_ID,
    violations: uniqueViolations,
    modulesCompleted,
    moduleRecords,
    input: agentInput,
    blueprint,
    planningSection: planningReport.section,
    confidence,
    retryCount,
    retryBranch,
    durationMs,
    kpis,
    pipelineMediated: true,
    lightingExcluded: true,
    goldenRuleSatisfied: PHOTOGRAPHY_DIRECTOR_AGENT_GOLDEN_RULE.includes("believe the product"),
  };
}

export async function executePhotographyDirectorAgentWithPipeline(input: {
  agentInput?: PhotographyDirectorAgentInput;
  context?: PhotographyDirectorAgentContext;
}): Promise<PhotographyDirectorAgentExecutionReport> {
  const report = await executePhotographyDirectorAgent(input);
  if (!report.valid || !report.blueprint) return report;

  const pipelineValid =
    PHOTOGRAPHY_DIRECTOR_AGENT_PIPELINE.length === 2 &&
    PHOTOGRAPHY_DIRECTOR_AGENT_PIPELINE[0].to === "photography_director" &&
    PHOTOGRAPHY_DIRECTOR_AGENT_PIPELINE[1].to === "lighting_director";

  if (!pipelineValid) {
    report.violations.push(violation("DIRECT_AGENT_HANDOFF", "Pipeline position chain is invalid"));
    report.valid = false;
  }

  if (report.agentId !== COMMERCIAL_PHOTO_DIRECTOR_ID) {
    report.violations.push(violation("EXECUTION_FAILED", "Agent must use commercial-photo-director contract"));
    report.valid = false;
  }

  return report;
}

function dedupeViolations(violations: PhotographyDirectorAgentViolation[]): PhotographyDirectorAgentViolation[] {
  const seen = new Set<string>();
  return violations.filter((v) => {
    const key = `${v.code}:${v.module ?? ""}:${v.message}`;
    if (seen.has(key)) return false;
    seen.add(key);
    return true;
  });
}

export function validatePhotographyDirectorAgentStructure(): PhotographyDirectorAgentViolation[] {
  if (PHOTOGRAPHY_DIRECTOR_AGENT_MODULES.length !== 7) {
    return [violation("MODULE_INCOMPLETE", "Photography Director Agent requires 7 internal modules")];
  }
  return [];
}

export function validatePhotographyDirectorAgent(
  context: PhotographyDirectorAgentContext = {},
): PhotographyDirectorAgentValidationReport {
  const violations = [...validatePhotographyDirectorAgentStructure()];
  return {
    valid: violations.length === 0,
    violations,
    modulesComplete: validatePhotographyDirectorAgentStructure().length === 0,
    pipelinePositionValid: PHOTOGRAPHY_DIRECTOR_AGENT_PIPELINE[1].to === "lighting_director",
    kitchenExecutionValid: false,
    successCriteriaMet: violations.length === 0,
  };
}

export async function validatePhotographyDirectorAgentWithExecution(
  context: PhotographyDirectorAgentContext = {},
): Promise<PhotographyDirectorAgentValidationReport> {
  const report = validatePhotographyDirectorAgent(context);
  const kitchen = await executePhotographyDirectorAgent({
    agentInput: buildBatterySprayerPhotographyDirectorInput(),
    context,
  });
  const violations = dedupeViolations([...report.violations, ...kitchen.violations]);
  return {
    ...report,
    valid: violations.length === 0 && kitchen.valid,
    violations,
    kitchenExecutionValid: kitchen.valid,
    successCriteriaMet: violations.length === 0 && kitchen.valid,
  };
}

export function assertPhotographyDirectorAgent(
  context?: PhotographyDirectorAgentContext,
): PhotographyDirectorAgentValidationReport {
  const report = validatePhotographyDirectorAgent(context);
  if (!report.valid) {
    throw new Error(`Photography Director Agent violated: ${report.violations.map((v) => v.message).join("; ")}`);
  }
  return report;
}

export async function runPhotographyDirectorAgent(
  context: PhotographyDirectorAgentContext = {},
): Promise<PhotographyDirectorAgentValidationReport> {
  return validatePhotographyDirectorAgentWithExecution(context);
}

export function isPhotographyDirectorAgentFailure(code: string): code is PhotographyDirectorAgentFailureCode {
  const codes: PhotographyDirectorAgentFailureCode[] = [
    "MODULE_INCOMPLETE",
    "RANDOM_CAMERA_PARAMS",
    "PERSPECTIVE_COMPOSITION_CONFLICT",
    "ARTIFICIAL_PHOTOGRAPHY",
    "MISSING_LIGHTING_STRATEGY",
    "HERO_LOSES_ADVANTAGE",
    "CATALOG_SHOOTING_MISMATCH",
    "STORY_STYLE_MISMATCH",
    "BLUEPRINT_INCOMPLETE",
    "LOW_CONFIDENCE",
    "LOW_REALISM",
    "RETRY_EXHAUSTED",
    "DESIGN_DECISION_DETECTED",
    "CONTAINS_COMPOSITION_DECISION",
    "DIRECT_AGENT_HANDOFF",
    "EXECUTION_FAILED",
  ];
  return codes.includes(code as PhotographyDirectorAgentFailureCode);
}

export function getPhotographyDirectorAgentModule(
  moduleId: PhotographyDirectorAgentModuleId,
): PhotographyDirectorAgentModuleDefinition | undefined {
  return PHOTOGRAPHY_DIRECTOR_AGENT_MODULES.find((m) => m.id === moduleId);
}

export function scorePhotographyCandidateForStory(
  candidate: string,
  storyPattern: string,
): number {
  if (candidate.includes("Outdoor") && storyPattern.includes("Problem")) return 0.96;
  if (candidate.includes("Lifestyle") && storyPattern.includes("Problem")) return 0.94;
  if (candidate.includes("Premium") && storyPattern.includes("Premium")) return 0.93;
  return 0.82;
}

export function validatePhotographySupportsStory(
  shootingType: string,
  storyPrimaryMessage: string,
): boolean {
  if (storyPrimaryMessage.toLowerCase().includes("tree") || storyPrimaryMessage.toLowerCase().includes("garden")) {
    return !/catalog/i.test(shootingType);
  }
  return shootingType.length > 0;
}

export function isInUseWorkflowShooting(shootingType: string): boolean {
  return shootingType === "in_use_workflow" || shootingType === "commercial_lifestyle";
}
